/* BEWARE: This file was generated by pg-nano. Any changes you make will be overwritten. */
import {
  bindQueryRow,
  bindQueryRowList,
  bindQueryRowOrNull,
  bindQueryValue,
} from 'pg-nano'
import * as t from './typeData.js'
import { Timestamp, JSON, Point, Range } from '@pg-nano/plugin-typebox/types'
import { type Static, type SchemaOptions, Type } from '@sinclair/typebox'

export { Timestamp, JSON, Point, Range }

export type StatusType = Static<typeof StatusType>
export const StatusType = /* @__PURE__ */ Type.Union([
  Type.Literal('pending'),
  Type.Literal('active'),
  Type.Literal('inactive'),
  Type.Literal('archived'),
])

export type AddressType = Static<typeof AddressType>
export const AddressType = /* @__PURE__ */ Type.Object({
  street: Type.Optional(Type.String()),
  city: Type.Optional(Type.String()),
  state: Type.Optional(Type.String()),
  zipCode: Type.Optional(Type.String()),
})

export type Account = Static<ReturnType<typeof Account>>
export const Account = (options?: SchemaOptions) =>
  Type.Object(
    {
      id: Type.Number(),
      username: Type.String(),
      email: Type.String(),
      passwordHash: Type.String(),
      postsCount: Type.Number(),
      firstName: Type.Optional(Type.String()),
      lastName: Type.Optional(Type.String()),
      dateOfBirth: Type.Optional(Type.String()),
      createdAt: Timestamp,
      updatedAt: Timestamp,
      lastLogin: Type.Optional(Timestamp),
      isDeleted: Type.Optional(Type.Boolean()),
    },
    options,
  )

export declare namespace Account {
  export type InsertParams = Static<ReturnType<typeof Account.InsertParams>>

  export type UpsertParams = Static<ReturnType<typeof Account.UpsertParams>>
}
Account.InsertParams = (options?: SchemaOptions) =>
  Type.Object(
    {
      id: Type.Optional(Type.Number()),
      username: Type.String(),
      email: Type.String(),
      passwordHash: Type.String(),
      postsCount: Type.Optional(Type.Number()),
      firstName: Type.Optional(Type.String()),
      lastName: Type.Optional(Type.String()),
      dateOfBirth: Type.Optional(Type.String()),
      createdAt: Type.Optional(Timestamp),
      updatedAt: Type.Optional(Timestamp),
      lastLogin: Type.Optional(Timestamp),
      isDeleted: Type.Optional(Type.Boolean()),
    },
    options,
  )

Account.UpsertParams = (options?: SchemaOptions) =>
  Type.Intersect(
    [
      Account.InsertParams(),
      Type.Object({
        id: Type.Number(),
      }),
    ],
    options,
  )

export type Course = Static<ReturnType<typeof Course>>
export const Course = (options?: SchemaOptions) =>
  Type.Object(
    {
      id: Type.Number(),
      courseName: Type.String(),
    },
    options,
  )

export declare namespace Course {
  export type InsertParams = Static<ReturnType<typeof Course.InsertParams>>

  export type UpsertParams = Static<ReturnType<typeof Course.UpsertParams>>
}
Course.InsertParams = (options?: SchemaOptions) =>
  Type.Object(
    {
      courseName: Type.String(),
    },
    options,
  )

Course.UpsertParams = (options?: SchemaOptions) =>
  Type.Intersect(
    [
      Course.InsertParams(),
      Type.Object({
        id: Type.Number(),
      }),
    ],
    options,
  )

export type CourseEnrollment = Static<ReturnType<typeof CourseEnrollment>>
export const CourseEnrollment = (options?: SchemaOptions) =>
  Type.Object(
    {
      studentId: Type.Number(),
      courseId: Type.Number(),
      enrollmentDate: Type.String(),
      grade: Type.Optional(Type.String()),
    },
    options,
  )

export declare namespace CourseEnrollment {
  export type InsertParams = Static<
    ReturnType<typeof CourseEnrollment.InsertParams>
  >

  export type UpsertParams = Static<
    ReturnType<typeof CourseEnrollment.UpsertParams>
  >
}
CourseEnrollment.InsertParams = (options?: SchemaOptions) =>
  Type.Object(
    {
      studentId: Type.Number(),
      courseId: Type.Number(),
      enrollmentDate: Type.String(),
      grade: Type.Optional(Type.String()),
    },
    options,
  )

CourseEnrollment.UpsertParams = (options?: SchemaOptions) =>
  Type.Intersect(
    [
      CourseEnrollment.InsertParams(),
      Type.Object({
        studentId: Type.Number(),
        courseId: Type.Number(),
      }),
    ],
    options,
  )

export type Foo = Static<ReturnType<typeof Foo>>
export const Foo = (options?: SchemaOptions) =>
  Type.Object(
    {
      id: Type.Number(),
      name: Type.String(),
      description: Type.Optional(Type.String()),
      createdAt: Timestamp,
      updatedAt: Timestamp,
      isActive: Type.Boolean(),
      score: Type.Optional(Type.String()),
      tags: Type.Optional(Type.Array(Type.String())),
      matrix: Type.Optional(Type.Array(Type.Number())),
      metadata: Type.Optional(Type.Never()),
      colorPreference: Type.Optional(Type.String()),
      binaryData: Type.Optional(Type.Never()),
      coordinates: Type.Optional(Point),
      ipAddress: Type.Optional(Type.String()),
      macAddress: Type.Optional(Type.String()),
      priceRange: Type.Optional(Range(Type.Number())),
      schedule: Type.Optional(Range(Timestamp)),
      priority: Type.Optional(Type.Number()),
      uuid: Type.Optional(Type.String()),
      searchVector: Type.Optional(Type.String()),
      status: Type.Optional(StatusType),
      address: Type.Optional(AddressType),
      productAttributes: Type.Optional(Type.Unknown()),
    },
    options,
  )

export declare namespace Foo {
  export type InsertParams = Static<ReturnType<typeof Foo.InsertParams>>

  export type UpsertParams = Static<ReturnType<typeof Foo.UpsertParams>>
}
Foo.InsertParams = (options?: SchemaOptions) =>
  Type.Object(
    {
      name: Type.String(),
      description: Type.Optional(Type.String()),
      createdAt: Type.Optional(Timestamp),
      updatedAt: Type.Optional(Timestamp),
      isActive: Type.Optional(Type.Boolean()),
      score: Type.Optional(Type.String()),
      tags: Type.Optional(Type.Array(Type.String())),
      matrix: Type.Optional(Type.Array(Type.Number())),
      metadata: Type.Optional(Type.Never()),
      colorPreference: Type.Optional(Type.String()),
      binaryData: Type.Optional(Type.Never()),
      coordinates: Type.Optional(Point),
      ipAddress: Type.Optional(Type.String()),
      macAddress: Type.Optional(Type.String()),
      priceRange: Type.Optional(Range(Type.Number())),
      schedule: Type.Optional(Range(Timestamp)),
      priority: Type.Optional(Type.Number()),
      uuid: Type.Optional(Type.String()),
      searchVector: Type.Optional(Type.String()),
      status: Type.Optional(StatusType),
      address: Type.Optional(AddressType),
      productAttributes: Type.Optional(Type.Unknown()),
    },
    options,
  )

Foo.UpsertParams = (options?: SchemaOptions) =>
  Type.Intersect(
    [
      Foo.InsertParams(),
      Type.Object({
        id: Type.Number(),
      }),
    ],
    options,
  )

export type Post = Static<ReturnType<typeof Post>>
export const Post = (options?: SchemaOptions) =>
  Type.Object(
    {
      id: Type.Number(),
      title: Type.String(),
      content: Type.Optional(Type.String()),
      authorId: Type.Optional(Type.Number()),
      createdAt: Type.Optional(Timestamp),
      updatedAt: Type.Optional(Timestamp),
    },
    options,
  )

export declare namespace Post {
  export type InsertParams = Static<ReturnType<typeof Post.InsertParams>>

  export type UpsertParams = Static<ReturnType<typeof Post.UpsertParams>>
}
Post.InsertParams = (options?: SchemaOptions) =>
  Type.Object(
    {
      id: Type.Optional(Type.Number()),
      title: Type.String(),
      content: Type.Optional(Type.String()),
      authorId: Type.Optional(Type.Number()),
      createdAt: Type.Optional(Timestamp),
      updatedAt: Type.Optional(Timestamp),
    },
    options,
  )

Post.UpsertParams = (options?: SchemaOptions) =>
  Type.Intersect(
    [
      Post.InsertParams(),
      Type.Object({
        id: Type.Number(),
      }),
    ],
    options,
  )

export type Student = Static<ReturnType<typeof Student>>
export const Student = (options?: SchemaOptions) =>
  Type.Object(
    {
      id: Type.Number(),
      firstName: Type.String(),
      lastName: Type.String(),
    },
    options,
  )

export declare namespace Student {
  export type InsertParams = Static<ReturnType<typeof Student.InsertParams>>

  export type UpsertParams = Static<ReturnType<typeof Student.UpsertParams>>
}
Student.InsertParams = (options?: SchemaOptions) =>
  Type.Object(
    {
      firstName: Type.String(),
      lastName: Type.String(),
    },
    options,
  )

Student.UpsertParams = (options?: SchemaOptions) =>
  Type.Intersect(
    [
      Student.InsertParams(),
      Type.Object({
        id: Type.Number(),
      }),
    ],
    options,
  )
export declare namespace calculateGpa {
  type Params = { studentId: number }
  type Result = { totalGpa: string }
}

export const calculateGpa = /* @__PURE__ */ bindQueryRowOrNull<
  calculateGpa.Params,
  calculateGpa.Result
>('calculate_gpa', $ => $.arity(1, 1).namedArgs(['studentId']).returnsRecord())

export declare namespace createAccount {
  type Params = {
    username: string
    email: string
    password: string
    salt: string
    firstName?: string
    lastName?: string
    dateOfBirth?: string
  }
  type Result = number
}

export const createAccount = /* @__PURE__ */ bindQueryValue<
  createAccount.Params,
  createAccount.Result
>('create_account', $ =>
  $.arity(4, 7).namedArgs([
    'username',
    'email',
    'password',
    'salt',
    'firstName',
    'lastName',
    'dateOfBirth',
  ]),
)

export declare namespace createCourse {
  type Params = [Course.InsertParams]
  type Result = Course
}

export const createCourse = /* @__PURE__ */ bindQueryRow<
  createCourse.Params,
  createCourse.Result
>('create_course', $ =>
  $.arity(1, 1).mapInput(0, t.insert_mapper(t.course)).returnsRecord(),
)

export declare namespace createCourseEnrollment {
  type Params = [CourseEnrollment.InsertParams]
  type Result = CourseEnrollment
}

export const createCourseEnrollment = /* @__PURE__ */ bindQueryRow<
  createCourseEnrollment.Params,
  createCourseEnrollment.Result
>('create_course_enrollment', $ =>
  $.arity(1, 1)
    .mapInput(0, t.insert_mapper(t.course_enrollment))
    .returnsRecord(),
)

export declare namespace createFoo {
  type Params = [Foo.InsertParams]
  type Result = Foo
}

export const createFoo = /* @__PURE__ */ bindQueryRow<
  createFoo.Params,
  createFoo.Result
>('create_foo', $ =>
  $.arity(1, 1)
    .mapInput(0, t.insert_mapper(t.foo))
    .returnsRecord()
    .mapOutput('address', t.insert_mapper(t.foo)),
)

export declare namespace createPost {
  type Params = { title: string; content: string; authorId: number }
  type Result = void
}

export const createPost = /* @__PURE__ */ bindQueryValue<
  createPost.Params,
  createPost.Result
>('create_post', $ => $.arity(3, 3).namedArgs(['title', 'content', 'authorId']))

export declare namespace createStudent {
  type Params = [Student.InsertParams]
  type Result = Student
}

export const createStudent = /* @__PURE__ */ bindQueryRow<
  createStudent.Params,
  createStudent.Result
>('create_student', $ =>
  $.arity(1, 1).mapInput(0, t.insert_mapper(t.student)).returnsRecord(),
)

export declare namespace deleteAccount {
  type Params = [number]
  type Result = boolean
}

export const deleteAccount = /* @__PURE__ */ bindQueryValue<
  deleteAccount.Params,
  deleteAccount.Result
>('delete_account', $ => $.arity(1, 1))

export declare namespace deleteCourse {
  type Params = { id: number }
  type Result = boolean
}

export const deleteCourse = /* @__PURE__ */ bindQueryValue<
  deleteCourse.Params,
  deleteCourse.Result
>('delete_course', $ => $.arity(1, 1).namedArgs(['id']))

export declare namespace deleteCourseEnrollment {
  type Params = { studentId: number; courseId: number }
  type Result = boolean
}

export const deleteCourseEnrollment = /* @__PURE__ */ bindQueryValue<
  deleteCourseEnrollment.Params,
  deleteCourseEnrollment.Result
>('delete_course_enrollment', $ =>
  $.arity(2, 2).namedArgs(['studentId', 'courseId']),
)

export declare namespace deleteFoo {
  type Params = { id: number }
  type Result = boolean
}

export const deleteFoo = /* @__PURE__ */ bindQueryValue<
  deleteFoo.Params,
  deleteFoo.Result
>('delete_foo', $ => $.arity(1, 1).namedArgs(['id']))

export declare namespace deletePost {
  type Params = { id: number }
  type Result = boolean
}

export const deletePost = /* @__PURE__ */ bindQueryValue<
  deletePost.Params,
  deletePost.Result
>('delete_post', $ => $.arity(1, 1).namedArgs(['id']))

export declare namespace deleteStudent {
  type Params = { id: number }
  type Result = boolean
}

export const deleteStudent = /* @__PURE__ */ bindQueryValue<
  deleteStudent.Params,
  deleteStudent.Result
>('delete_student', $ => $.arity(1, 1).namedArgs(['id']))

export declare namespace dropAccountNamed {
  type Params = { username: string }
  type Result = unknown
}

export const dropAccountNamed = /* @__PURE__ */ bindQueryValue<
  dropAccountNamed.Params,
  dropAccountNamed.Result
>('drop_account_named', $ => $.arity(1, 1).namedArgs(['username']))

export declare namespace getAccount {
  type Params = { id: number }
  type Result = Account
}

export const getAccount = /* @__PURE__ */ bindQueryRowOrNull<
  getAccount.Params,
  getAccount.Result
>('get_account', $ => $.arity(1, 1).namedArgs(['id']).returnsRecord())

export declare namespace getCourse {
  type Params = { id: number }
  type Result = Course
}

export const getCourse = /* @__PURE__ */ bindQueryRowOrNull<
  getCourse.Params,
  getCourse.Result
>('get_course', $ => $.arity(1, 1).namedArgs(['id']).returnsRecord())

export declare namespace getCourseEnrollment {
  type Params = { studentId: number; courseId: number }
  type Result = CourseEnrollment
}

export const getCourseEnrollment = /* @__PURE__ */ bindQueryRowOrNull<
  getCourseEnrollment.Params,
  getCourseEnrollment.Result
>('get_course_enrollment', $ =>
  $.arity(2, 2).namedArgs(['studentId', 'courseId']).returnsRecord(),
)

export declare namespace getFoo {
  type Params = { id: number }
  type Result = Foo
}

export const getFoo = /* @__PURE__ */ bindQueryRowList<
  getFoo.Params,
  getFoo.Result
>('get_foo', $ =>
  $.arity(1, 1).namedArgs(['id']).mapOutput('address', t.address_type),
)

export declare namespace getPost {
  type Params = { id: number }
  type Result = Post
}

export const getPost = /* @__PURE__ */ bindQueryRowOrNull<
  getPost.Params,
  getPost.Result
>('get_post', $ => $.arity(1, 1).namedArgs(['id']).returnsRecord())

export declare namespace getStudent {
  type Params = { id: number }
  type Result = Student
}

export const getStudent = /* @__PURE__ */ bindQueryRowOrNull<
  getStudent.Params,
  getStudent.Result
>('get_student', $ => $.arity(1, 1).namedArgs(['id']).returnsRecord())

export declare namespace updateAccount {
  type Params = [number, Partial<Account>]
  type Result = Account
}

export const updateAccount = /* @__PURE__ */ bindQueryRow<
  updateAccount.Params,
  updateAccount.Result
>('update_account', $ =>
  $.arity(2, 2).mapInput(1, t.update_mapper).returnsRecord(),
)

export declare namespace updateCourse {
  type Params = [number, Partial<Course>]
  type Result = Course
}

export const updateCourse = /* @__PURE__ */ bindQueryRow<
  updateCourse.Params,
  updateCourse.Result
>('update_course', $ =>
  $.arity(2, 2).mapInput(1, t.update_mapper).returnsRecord(),
)

export declare namespace updateCourseEnrollment {
  type Params = [number, number, Partial<CourseEnrollment>]
  type Result = CourseEnrollment
}

export const updateCourseEnrollment = /* @__PURE__ */ bindQueryRow<
  updateCourseEnrollment.Params,
  updateCourseEnrollment.Result
>('update_course_enrollment', $ =>
  $.arity(3, 3).mapInput(2, t.update_mapper).returnsRecord(),
)

export declare namespace updateFoo {
  type Params = [number, Partial<Foo>]
  type Result = Foo
}

export const updateFoo = /* @__PURE__ */ bindQueryRow<
  updateFoo.Params,
  updateFoo.Result
>('update_foo', $ =>
  $.arity(2, 2)
    .mapInput(1, t.update_mapper)
    .returnsRecord()
    .mapOutput('address', t.address_type),
)

export declare namespace updatePost {
  type Params = [number, Partial<Post>]
  type Result = Post
}

export const updatePost = /* @__PURE__ */ bindQueryRow<
  updatePost.Params,
  updatePost.Result
>('update_post', $ =>
  $.arity(2, 2).mapInput(1, t.update_mapper).returnsRecord(),
)

export declare namespace updateStudent {
  type Params = [number, Partial<Student>]
  type Result = Student
}

export const updateStudent = /* @__PURE__ */ bindQueryRow<
  updateStudent.Params,
  updateStudent.Result
>('update_student', $ =>
  $.arity(2, 2).mapInput(1, t.update_mapper).returnsRecord(),
)

export declare namespace upsertAccount {
  type Params = [Account.UpsertParams]
  type Result = Account
}

export const upsertAccount = /* @__PURE__ */ bindQueryRow<
  upsertAccount.Params,
  upsertAccount.Result
>('upsert_account', $ =>
  $.arity(1, 1).mapInput(0, t.insert_mapper(t.account)).returnsRecord(),
)

export declare namespace upsertCourse {
  type Params = [Course.UpsertParams]
  type Result = Course
}

export const upsertCourse = /* @__PURE__ */ bindQueryRow<
  upsertCourse.Params,
  upsertCourse.Result
>('upsert_course', $ =>
  $.arity(1, 1).mapInput(0, t.insert_mapper(t.course)).returnsRecord(),
)

export declare namespace upsertCourseEnrollment {
  type Params = [CourseEnrollment.UpsertParams]
  type Result = CourseEnrollment
}

export const upsertCourseEnrollment = /* @__PURE__ */ bindQueryRow<
  upsertCourseEnrollment.Params,
  upsertCourseEnrollment.Result
>('upsert_course_enrollment', $ =>
  $.arity(1, 1)
    .mapInput(0, t.insert_mapper(t.course_enrollment))
    .returnsRecord(),
)

export declare namespace upsertFoo {
  type Params = [Foo.UpsertParams]
  type Result = Foo
}

export const upsertFoo = /* @__PURE__ */ bindQueryRow<
  upsertFoo.Params,
  upsertFoo.Result
>('upsert_foo', $ =>
  $.arity(1, 1)
    .mapInput(0, t.insert_mapper(t.foo))
    .returnsRecord()
    .mapOutput('address', t.insert_mapper(t.foo)),
)

export declare namespace upsertPost {
  type Params = [Post.UpsertParams]
  type Result = Post
}

export const upsertPost = /* @__PURE__ */ bindQueryRow<
  upsertPost.Params,
  upsertPost.Result
>('upsert_post', $ =>
  $.arity(1, 1).mapInput(0, t.insert_mapper(t.post)).returnsRecord(),
)

export declare namespace upsertStudent {
  type Params = [Student.UpsertParams]
  type Result = Student
}

export const upsertStudent = /* @__PURE__ */ bindQueryRow<
  upsertStudent.Params,
  upsertStudent.Result
>('upsert_student', $ =>
  $.arity(1, 1).mapInput(0, t.insert_mapper(t.student)).returnsRecord(),
)
